# Generated by Django 5.1.6 on 2025-03-12 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternatywny telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mailing_address', models.CharField(max_length=255, verbose_name='Adres korespondencyjny')),
                ('pesel', models.CharField(max_length=11, unique=True, verbose_name='PESEL')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa materiału')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nagrobek', 'Nagrobek'), ('oblozenie', 'Obłożenie'), ('podniesienie_nagrobka', 'Podniesienie nagrobka'), ('dopiska_po_pogrzebie', 'Dopiska po pogrzebie'), ('ekshumacja', 'Ekshumacja'), ('nowy_szablon', 'Nowy Szablon')], max_length=100, verbose_name='Nazwa szablonu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('position', models.CharField(max_length=100, verbose_name='Stanowisko')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('status', models.CharField(choices=[('wycena', 'Wycena'), ('przyjete', 'Przyjęte do realizacji'), ('realizacja', 'W realizacji'), ('platnosc', 'Czeka na płatność'), ('zakonczone', 'Zakończone')], default='wycena', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('street', models.CharField(max_length=100, verbose_name='Ulica')),
                ('plot', models.CharField(max_length=100, verbose_name='Kwatera')),
                ('grave_type', models.CharField(choices=[('ziemna', 'Ziemna'), ('grobowiec', 'Grobowiec')], max_length=50, verbose_name='Typ mogiły')),
                ('grave_size', models.CharField(choices=[('pojedynczy', 'Pojedynczy'), ('poltorak', 'Półtorak'), ('podwojny', 'Podwójny')], max_length=50, verbose_name='Rozmiar grobu')),
                ('border', models.BooleanField(default=False, verbose_name='Obwódka')),
                ('border_dimensions', models.CharField(max_length=100, verbose_name='Wymiary obwódki')),
                ('border_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena obwódki')),
                ('frame', models.BooleanField(default=False, verbose_name='Rama')),
                ('frame_height', models.CharField(max_length=100, verbose_name='Wysokość ramy')),
                ('frame_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena ramy')),
                ('main_plate', models.BooleanField(default=False, verbose_name='Płyta główna')),
                ('main_plate_dimensions', models.CharField(max_length=100, verbose_name='Wymiary płyty głównej')),
                ('main_plate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena płyty głównej')),
                ('lamp', models.BooleanField(default=False, verbose_name='Lampion')),
                ('lamp_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena lampionu')),
                ('vase', models.BooleanField(default=False, verbose_name='Wazon')),
                ('vase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena wazonu')),
                ('ball', models.BooleanField(default=False, verbose_name='Kula')),
                ('ball_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena kuli')),
                ('other_accessories', models.TextField(blank=True, null=True, verbose_name='Inne akcesoria')),
                ('inscription', models.TextField(blank=True, null=True, verbose_name='Litery')),
                ('letter_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kolor liter')),
                ('font', models.CharField(blank=True, max_length=50, null=True, verbose_name='Czcionka')),
                ('inscription_image', models.ImageField(blank=True, null=True, upload_to='inscription_images/', verbose_name='Zdjęcie z rozkładu treści tablicy')),
                ('covering', models.BooleanField(default=False, verbose_name='Obłożenie')),
                ('covering_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena m2')),
                ('covering_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ilość m2')),
                ('curbs_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena mb')),
                ('curbs_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ilość mb')),
                ('monument_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszt wykonania')),
                ('old_monument_removal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Demontaż starego')),
                ('cemetery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Opłata cmentarna')),
                ('transport_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszt transportu')),
                ('other_costs', models.TextField(blank=True, null=True, verbose_name='Koszta inne')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Suma kosztów')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Termin wykonania nagrobka')),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zaliczka')),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Karta'), ('cash', 'Gotówka'), ('transfer', 'Przelew w ciągu 3 dni')], max_length=50, null=True, verbose_name='Metoda płatności')),
                ('border_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='border_material', to='orders.material')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.client')),
                ('frame_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_material', to='orders.material')),
                ('main_plate_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_plate_material', to='orders.material')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.ordertemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('date', models.DateField(verbose_name='Data')),
                ('method', models.CharField(choices=[('card', 'Karta'), ('cash', 'Gotówka'), ('transfer', 'Przelew')], max_length=50, verbose_name='Metoda płatności')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_photos/', verbose_name='Zdjęcie')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='Brak opisu')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images/', verbose_name='Zdjęcie')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa podzadania')),
                ('completed', models.BooleanField(default=False, verbose_name='Wykonane')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='orders.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa zadania')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis zadania')),
                ('order_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='orders.ordertemplate')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.tasktemplate'),
        ),
    ]
