# Generated by Django 5.1.6 on 2025-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa zadania'),
        ),
    ]
