# Generated by Django 5.1.6 on 2025-03-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_tasktemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_accessories_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena innych akcesoriów'),
        ),
        migrations.AddField(
            model_name='order',
            name='other_costs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszta inne'),
        ),
    ]
