# Generated by Django 5.1.6 on 2025-03-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_other_accessories_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='border_dimensions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='border_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='frame_height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='frame_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='main_plate_dimensions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='main_plate_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='curbs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Krawężniki Cena'),
        ),
    ]
