# Generated by Django 5.1.6 on 2025-03-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_border_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='border',
        ),
        migrations.RemoveField(
            model_name='order',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='order',
            name='main_plate',
        ),
    ]
