# Generated by Django 5.1.6 on 2025-03-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_border_remove_order_frame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='covering_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='curbs_price',
        ),
        migrations.AddField(
            model_name='order',
            name='covering_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszt obłożenia'),
        ),
        migrations.AddField(
            model_name='order',
            name='covering_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_material', to='orders.material'),
        ),
    ]
