# Generated by Django 5.1.6 on 2025-03-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_covering_price_remove_order_curbs_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='curbs_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ilość mb krawężnika'),
        ),
    ]
