# Generated by Django 5.1.6 on 2025-03-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_template',
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
