# Generated by Django 5.1.6 on 2025-03-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_task_task_template_delete_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.ordertemplate'),
        ),
        migrations.DeleteModel(
            name='TaskTemplate',
        ),
    ]
